# .cnb.yml
master: # 触发分支
  push: # 触发事件，对应一个构建，可以包含多条 Pipeline。即可以是数组，也可以是对象。
    - env:
        # 直接声明静态字符串变量（值用双引号包裹）
        artifact_name1: szseinnovation100index
        artifact_name2: szseinnovation100indexcn
        artifact_name3: aiindex
        artifact_name4: aiindexcn
      services:
        - docker
      stages: # 流水线1
        - name: build-with-param1
          script: |
             docker build -f Dockerfile20 -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${artifact_name1}:latest .
             docker build -f Dockerfile20cn -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${artifact_name2}:latest .
             docker build -f Dockerfilea20 -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${artifact_name3}:latest .
             docker build -f Dockerfilea20cn -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${artifact_name4}:latest .
        - name: push-with-param1
          script: |
             - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${artifact_name1}:latest
             - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${artifact_name2}:latest
             - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${artifact_name3}:latest
             - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${artifact_name4}:latest
