practiceforusers*:
  tag_push:
    - env:
        artifact_name: szseinnovation100etfprac
      services:
        - docker
      stages:
        - echo "即将推送的镜像路径：${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}0${artifact_name}:latest"
        - echo "第一个变量的取值： ${CNB_DOCKER_REGISTRY}"
        - echo "第二个变量的取值前20位：${CNB_REPO_SLUG_LOWERCASE:0:21}"
        - echo "我定义的变量之取值：${artifact_name}"
        - name: build-with-param1
          script: |
            echo "静态字符串变量值：${artifact_name}"
            docker build -f Dockerfile2simpleusers -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}0/${artifact_name}:$CNB_BRANCH       .
        - name: push-with-param1
          script:
            docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}0/${artifact_name}:$CNB_BRANCH