master:
  web_trigger_one:
    - env:
        artifact_name: insertvalue
      services:
        - docker
      stages:
        - >-
          echo
          "即将推送的镜像路径：${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}0${artifact_name}:latest"
        - echo "第一个变量的取值： ${CNB_DOCKER_REGISTRY}"
        - echo "第二个变量的取值前20位：${CNB_REPO_SLUG_LOWERCASE:0:21}"
        - echo "我定义的变量之取值：${artifact_name}"
        - name: build-with-param1
          script: >
            echo "静态字符串变量值：${artifact_name}"
            docker build -f Dockerfile00 -t
            ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}0/${artifact_name}:latest          .
        - name: push-with-param1
          script:
            - >-
              docker push
              ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}0/${artifact_name}:latest