# .cnb.yml
master: # 触发分支
  push: # 触发事件，对应一个构建，可以包含多条 Pipeline。即可以是数组，也可以是对象。
    - env:
        # 直接声明静态字符串变量（值用双引号包裹）
        artifact_name: insertvalue
      services:
        - docker
      stages: # 流水线1
        - echo "即将推送的镜像路径：${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}${artifact_name}:latest"
        - echo "第一个变量的取值： ${CNB_DOCKER_REGISTRY}"
        - echo "第二个变量的取值前20位：${CNB_REPO_SLUG_LOWERCASE:0:21}"
        - echo "我定义的变量之取值：${artifact_name}"
        - name: build-with-param
          script: |
             echo "静态字符串变量值：${artifact_name}"
             docker build -f Dockerfile00 -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${artifact_name}:latest .
        - name: push-with-param
          script:
             - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}/${artifact_name}:latest
