# .cnb.yml
variables:
  artifact_name:insertvalue
master: # 触发分支
  push: # 触发事件，对应一个构建，可以包含多条 Pipeline。即可以是数组，也可以是对象。
    - services:
        - docker
      stages: # 流水线1
        - echo "即将推送的镜像路径：${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}${artifact_name}:latest"
        - echo "第一个变量的取值： ${CNB_DOCKER_REGISTRY}"
        - echo "第二个变量的取值：${CNB_REPO_SLUG_LOWERCASE}"
        - echo "我定义的变量之取值：${artifact_name}"
        - name: build-with-param
          script:
             - docker build -f Dockerfile00 -t ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}${artifact_name}:latest .
        - name: push-with-param
          script:
             - docker push ${CNB_DOCKER_REGISTRY}/${CNB_REPO_SLUG_LOWERCASE}${artifact_name}:latest